{
  "$GMRoomUI":"",
  "%Name":"RoomUI",
  "children":[
    {"$GMRUILayer":"v1","%Name":"UILayer_ajustes","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"fundo_ajustes","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"FlexPanel_botoes","alignContent":2,"alignItems":2,"alignSelf":1,"children":[
                {"$GMRFlexPanel":"","%Name":"FlexPanel_musica","alignItems":2,"children":[
                    {"$GMRTextItem":"v3","%Name":"text_71D7B0C4","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_desligar_musica","path":"fonts/fnt_txt_desligar_musica/fnt_txt_desligar_musica.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_71D7B0C4","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"MUSICA","wrap":false,"x":40.0,"y":-68.0,},
                    {"$GMRInstance":"v4","%Name":"inst_4C978F7D","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_4C978F7D","objectId":{"name":"obj_btn_desativar_sfx","path":"objects/obj_btn_desativar_sfx/obj_btn_desativar_sfx.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":16.0,"y":-9.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_musica","nodeColour":4293347570,"paddingBottom":{"unit":1,"value":5.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_sfx","alignItems":2,"children":[
                    {"$GMRFlexPanel":"","%Name":"FlexPanel_10","alignItems":2,"alignSelf":2,"children":[],"flexDirection":0,"height":{"unit":3,"value":25.0,},"justifyContent":1,"name":"FlexPanel_10","nodeColour":4294068328,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":142.0,},},
                    {"$GMRTextItem":"v3","%Name":"text_6ACB82E0","alignment":1,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_desligar_som","path":"fonts/fnt_txt_desligar_som/fnt_txt_desligar_som.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_6ACB82E0","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"EFEITOS","wrap":false,"x":0.0,"y":-55.0,},
                    {"$GMRInstance":"v4","%Name":"inst_38CBB817","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_38CBB817","objectId":{"name":"obj_btn_desativar_musica","path":"objects/obj_btn_desativar_musica/obj_btn_desativar_musica.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":-24.0,"y":-96.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_sfx","nodeColour":4282970806,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
              ],"flexDirection":0,"height":{"unit":3,"value":39.68,},"justifyContent":1,"name":"FlexPanel_botoes","nodeColour":4291555912,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":80.0,},},
            {"$GMRInstance":"v4","%Name":"inst_16695801","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":1,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_16695801","objectId":{"name":"obj_btn_voltar_tela_inicial","path":"objects/obj_btn_voltar_tela_inicial/obj_btn_voltar_tela_inicial.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":-40.0,"y":201.0,},
            {"$GMRTextItem":"v3","%Name":"text_BDB0C09","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":1,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_configuracoes","path":"fonts/fnt_txt_configuracoes/fnt_txt_configuracoes.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_BDB0C09","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"AJUSTES","wrap":false,"x":-50.0,"y":24.0,},
            {"$GMRSpriteGraphic":"v1","%Name":"graphic_2DAE0A5","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":4,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"headPosition":0.0,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_2DAE0A5","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"spr_bloco_pause","path":"sprites/spr_bloco_pause/spr_bloco_pause.yy",},"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":2,"value":93.18,},"justifyContent":1,"name":"fundo_ajustes","nodeColour":4294101832,"paddingLeft":{"unit":1,"value":40.0,},"paddingRight":{"unit":1,"value":50.0,},"paddingTop":{"unit":1,"value":50.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":2,"value":53.12,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_ajustes","nodeColour":4288301298,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"UILayer_pause_menu","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_menu","alignItems":2,"alignSelf":1,"children":[
            {"$GMRFlexPanel":"","%Name":"fundo","alignItems":2,"alignSelf":2,"children":[
                {"$GMRFlexPanel":"","%Name":"FlexPanel_bnt_retomar","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_7B60A625","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_7B60A625","objectId":{"name":"obj_retomar_jogo","path":"objects/obj_retomar_jogo/obj_retomar_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_bnt_retomar","nodeColour":4282938866,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_5","alignItems":2,"children":[
                    {"$GMRFlexPanel":"","%Name":"FlexPanel_9","alignItems":2,"children":[
                        {"$GMRInstance":"v4","%Name":"inst_9D6422","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_9D6422","objectId":{"name":"obj_btn_ajustes_jogo","path":"objects/obj_btn_ajustes_jogo/obj_btn_ajustes_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                      ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_9","nodeColour":4294098760,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_5","nodeColour":4282968050,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_12","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_4F023565","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_4F023565","objectId":{"name":"obj_reiniciar_jogo","path":"objects/obj_reiniciar_jogo/obj_reiniciar_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_12","nodeColour":4294068412,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_fundo","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_638BB9F0","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_638BB9F0","objectId":{"name":"obj_btn_sair_da_fase","path":"objects/obj_btn_sair_da_fase/obj_btn_sair_da_fase.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_fundo","nodeColour":4282962418,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRTextItem":"v3","%Name":"text_677435DB","alignment":1,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":1,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_jogo_pausado_gameovercre","path":"fonts/fnt_txt_jogo_pausado_gameovercre/fnt_txt_jogo_pausado_gameovercre.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_677435DB","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"JOGO PAUSADO","wrap":false,"x":-80.5,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":1,"value":200.0,},"justifyContent":1,"name":"fundo","nodeColour":4294068440,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":190.0,},},
            {"$GMRInstance":"v4","%Name":"inst_22F14969","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":4,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":true,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_22F14969","objectId":{"name":"obj_menu_pause","path":"objects/obj_menu_pause/obj_menu_pause.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":1,"value":270.0,},"justifyContent":1,"name":"FlexPanel_menu","nodeColour":4282970842,"positionLeft":{"unit":1,"value":0.0,},"positionTop":{"unit":1,"value":0.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":480.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_pause_menu","nodeColour":4294092872,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"UILayer_fase_concluida","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_menu","alignItems":2,"alignSelf":2,"children":[
            {"$GMRFlexPanel":"","%Name":"fundo","alignItems":2,"alignSelf":2,"children":[
                {"$GMRFlexPanel":"","%Name":"FlexPanel_7","alignItems":2,"alignSelf":2,"children":[
                    {"$GMRTextItem":"v3","%Name":"text_55286B8","alignment":0,"charSpacing":0.0,"colour":4294920706,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_ui_fase_completa_gameovercre","path":"fonts/fnt_ui_fase_completa_gameovercre/fnt_ui_fase_completa_gameovercre.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_55286B8","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"MISSÃO CUMPRIDA!","wrap":false,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":20.0,},"justifyContent":1,"marginBottom":{"unit":1,"value":14.0,},"name":"FlexPanel_7","nodeColour":4282945778,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":88.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_bnt_retomar","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_18BACDA9","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_18BACDA9","objectId":{"name":"obj_reiniciar_jogo","path":"objects/obj_reiniciar_jogo/obj_reiniciar_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_bnt_retomar","nodeColour":4282938866,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_fundo","alignItems":2,"alignSelf":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_15F7C6D","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_15F7C6D","objectId":{"name":"obj_btn_sair_da_fase","path":"objects/obj_btn_sair_da_fase/obj_btn_sair_da_fase.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_fundo","nodeColour":4282962418,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
              ],"flexDirection":0,"height":{"unit":1,"value":200.0,},"justifyContent":1,"name":"fundo","nodeColour":4294068440,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":190.0,},},
          ],"flexDirection":0,"height":{"unit":1,"value":270.0,},"justifyContent":1,"name":"FlexPanel_menu","nodeColour":4282970842,"positionLeft":{"unit":1,"value":1.0,},"positionTop":{"unit":1,"value":0.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":480.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_fase_concluida","nodeColour":4294092872,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"UILayer_game_over","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_menu","alignItems":2,"alignSelf":2,"children":[
            {"$GMRFlexPanel":"","%Name":"fundo","alignItems":2,"alignSelf":2,"children":[
                {"$GMRFlexPanel":"","%Name":"FlexPanel_8","alignItems":2,"children":[
                    {"$GMRTextItem":"v3","%Name":"text_7D1F5C","alignment":256,"charSpacing":0.0,"colour":4279835135,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_ui_gameover_gameovercre","path":"fonts/fnt_ui_gameover_gameovercre/fnt_ui_gameover_gameovercre.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_7D1F5C","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"FIM DE JOGO","wrap":false,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":17.0,},"justifyContent":1,"marginBottom":{"unit":1,"value":7.0,},"name":"FlexPanel_8","nodeColour":4294100552,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_bnt_retomar","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_150CD05F","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_150CD05F","objectId":{"name":"obj_reiniciar_jogo","path":"objects/obj_reiniciar_jogo/obj_reiniciar_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_bnt_retomar","nodeColour":4282938866,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_fundo","alignItems":2,"alignSelf":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_140EC062","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_140EC062","objectId":{"name":"obj_btn_sair_da_fase","path":"objects/obj_btn_sair_da_fase/obj_btn_sair_da_fase.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_fundo","nodeColour":4282962418,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
              ],"flexDirection":0,"height":{"unit":1,"value":200.0,},"justifyContent":1,"name":"fundo","nodeColour":4294068440,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":190.0,},},
          ],"flexDirection":0,"height":{"unit":1,"value":270.0,},"justifyContent":1,"name":"FlexPanel_menu","nodeColour":4282970842,"positionLeft":{"unit":1,"value":1.0,},"positionTop":{"unit":1,"value":0.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":480.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_game_over","nodeColour":4294092872,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"UILayer_HUD","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_6","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"texto","alignItems":2,"alignSelf":1,"children":[
                {"$GMRTextItem":"v3","%Name":"text_61A7F943","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_ui_oxigenio_gameovercre","path":"fonts/fnt_ui_oxigenio_gameovercre/fnt_ui_oxigenio_gameovercre.yy",},"frameH":40.0,"frameW":68.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_61A7F943","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"OXIGÊNIO","wrap":false,"x":0.0,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":100.0,},"justifyContent":1,"name":"texto","nodeColour":4285592136,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
            {"$GMRFlexPanel":"","%Name":"barra_oxigenio","alignContent":2,"alignItems":2,"alignSelf":4,"children":[
                {"$GMRInstance":"v4","%Name":"inst_61998CD9","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_61998CD9","objectId":{"name":"obj_barra_oxigenio","path":"objects/obj_barra_oxigenio/obj_barra_oxigenio.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":41.0,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":0.0,},"justifyContent":1,"name":"barra_oxigenio","nodeColour":4282964722,"positionLeft":{"unit":0,"value":17.0,},"positionTop":{"unit":0,"value":33.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":2,"value":120.0,},},
            {"$GMRFlexPanel":"","%Name":"fundo_objetivos","alignItems":2,"alignSelf":4,"children":[
                {"$GMRSpriteGraphic":"v1","%Name":"graphic_13F3DF4F","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"headPosition":0.0,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_13F3DF4F","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":2.0,"scaleY":2.0,"spriteId":{"name":"spr_bloco_objetivos","path":"sprites/spr_bloco_objetivos/spr_bloco_objetivos.yy",},"x":47.5,"y":32.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":16.0,},"justifyContent":1,"marginTop":{"unit":1,"value":15.0,},"name":"fundo_objetivos","nodeColour":4283582706,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":2,"value":100.0,},},
          ],"flexDirection":0,"height":{"unit":3,"value":270.0,},"justifyContent":1,"name":"FlexPanel_6","nodeColour":4294068392,"positionLeft":{"unit":1,"value":9.0,},"positionTop":{"unit":1,"value":22.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":10.0,},},
        {"$GMRFlexPanel":"","%Name":"FlexPanel","alignItems":4,"children":[
            {"$GMRInstance":"v4","%Name":"inst_3DCEF8EC","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_3DCEF8EC","objectId":{"name":"obj_btn_pause","path":"objects/obj_btn_pause/obj_btn_pause.yy",},"previewSprite":{"name":"spr_btn_pausar_jogo","path":"sprites/spr_btn_pausar_jogo/spr_btn_pausar_jogo.yy",},"properties":[
                {"$GMOverriddenProperty":"v1","%Name":"","name":"","objectId":{"name":"obj_btn_pause","path":"objects/obj_btn_pause/obj_btn_pause.yy",},"propertyId":{"name":"sprite_index","path":"objects/obj_btn_pause/obj_btn_pause.yy",},"resourceType":"GMOverriddenProperty","resourceVersion":"2.0","value":"spr_btn_pausar_jogo",},
              ],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel","nodeColour":4287165000,"positionLeft":{"unit":1,"value":438.0,},"positionTop":{"unit":1,"value":18.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_HUD","nodeColour":4282960882,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"UILayer_Inicial","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_2","alignItems":2,"children":[
            {"$GMRInstance":"v4","%Name":"inst_D6225E4","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_D6225E4","objectId":{"name":"obj_btn_ajustes_jogo2","path":"objects/obj_btn_ajustes_jogo2/obj_btn_ajustes_jogo2.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":16.0,"y":16.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_2","nodeColour":4294068327,"positionBottom":{"unit":1,"value":12.0,},"positionLeft":{"unit":1,"value":15.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":32.0,},},
        {"$GMRFlexPanel":"","%Name":"MenuPanel","alignItems":2,"children":[
            {"$GMRFlexPanel":"","%Name":"FlexPanel_titulo_jogo","alignItems":2,"children":[
                {"$GMRTextItem":"v3","%Name":"text_7E9EEACA","alignment":1,"charSpacing":0.0,"colour":4292869903,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_titulo_jogo","path":"fonts/fnt_txt_titulo_jogo/fnt_txt_titulo_jogo.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":false,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_7E9EEACA","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"OCEAN GUARDIAN","wrap":false,"x":0.0,"y":0.0,},
              ],"flexDirection":0,"height":{"unit":3,"value":30.0,},"justifyContent":1,"name":"FlexPanel_titulo_jogo","nodeColour":4294100296,"paddingBottom":{"unit":1,"value":17.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":176.0,},},
            {"$GMRFlexPanel":"","%Name":"btn_start_panel","alignItems":2,"children":[
                {"$GMRFlexPanel":"","%Name":"Flex_panel_op_menu","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_7BF9EBD","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_7BF9EBD","objectId":{"name":"obj_btn_iniciar_jogo","path":"objects/obj_btn_iniciar_jogo/obj_btn_iniciar_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"Flex_panel_op_menu","nodeColour":4294068447,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":120.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_3","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_693BA7A6","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_693BA7A6","objectId":{"name":"obj_btn_creditos","path":"objects/obj_btn_creditos/obj_btn_creditos.yy",},"previewSprite":{"name":"spr_btn_creditos","path":"sprites/spr_btn_creditos/spr_btn_creditos.yy",},"properties":[
                        {"$GMOverriddenProperty":"v1","%Name":"","name":"","objectId":{"name":"obj_btn_creditos","path":"objects/obj_btn_creditos/obj_btn_creditos.yy",},"propertyId":{"name":"sprite_index","path":"objects/obj_btn_creditos/obj_btn_creditos.yy",},"resourceType":"GMOverriddenProperty","resourceVersion":"2.0","value":"spr_btn_creditos",},
                      ],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_3","nodeColour":4289284338,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":90.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_4","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_1C479AAB","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":true,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_1C479AAB","objectId":{"name":"obj_btn_ajustes_jogo","path":"objects/obj_btn_ajustes_jogo/obj_btn_ajustes_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_4","nodeColour":4294083912,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
                {"$GMRFlexPanel":"","%Name":"FlexPanel_1","alignItems":2,"children":[
                    {"$GMRInstance":"v4","%Name":"inst_70DBBBB7","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_70DBBBB7","objectId":{"name":"obj_btn_sair_jogo","path":"objects/obj_btn_sair_jogo/obj_btn_sair_jogo.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
                  ],"flexDirection":0,"height":{"unit":3,"value":32.0,},"justifyContent":1,"name":"FlexPanel_1","nodeColour":4294068299,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":90.0,},},
              ],"flexDirection":0,"gapColumn":1.0,"gapRow":3.0,"height":{"unit":3,"value":100.0,},"justifyContent":1,"name":"btn_start_panel","nodeColour":4293871858,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":100.0,},},
          ],"flexDirection":0,"gapRow":10.0,"height":{"unit":1,"value":123.0,},"justifyContent":1,"name":"MenuPanel","nodeColour":4285002312,"paddingRight":{"unit":1,"value":1.0,},"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":1,"value":225.0,},},
      ],"flexDirection":0,"gridX":32,"gridY":32,"justifyContent":1,"name":"UILayer_Inicial","nodeColour":4294068377,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
    {"$GMRUILayer":"v1","%Name":"UILayer_menu_creditos","alignItems":2,"children":[
        {"$GMRFlexPanel":"","%Name":"FlexPanel_13","alignItems":2,"children":[],"flexDirection":0,"height":{"unit":3,"value":16.0,},"justifyContent":1,"name":"FlexPanel_13","nodeColour":4288432370,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":16.0,},},
        {"$GMRFlexPanel":"","%Name":"FlexPanel_11","alignItems":2,"alignSelf":1,"children":[
            {"$GMRInstance":"v4","%Name":"inst_634973DF","colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"frozen":false,"hasCreationCode":false,"ignore":false,"imageIndex":0,"imageSpeed":1.0,"inheritCode":false,"inheritedItemId":null,"inheritItemSettings":false,"isDnd":false,"name":"inst_634973DF","objectId":{"name":"obj_btn_voltar_tela_inicial","path":"objects/obj_btn_voltar_tela_inicial/obj_btn_voltar_tela_inicial.yy",},"properties":[],"resourceType":"GMRInstance","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"x":0.0,"y":0.0,},
          ],"flexDirection":0,"height":{"unit":3,"value":80.0,},"justifyContent":1,"marginLeft":{"unit":1,"value":20.0,},"name":"FlexPanel_11","nodeColour":4287842546,"positionLeft":{"unit":1,"value":4.0,},"positionTop":{"unit":1,"value":26.0,},"positionType":2,"resourceType":"GMRFlexPanel","resourceVersion":"2.0","width":{"unit":3,"value":80.0,},},
        {"$GMRSpriteGraphic":"v1","%Name":"graphic_65618193","animationSpeed":1.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":4,"resourceType":"InstanceFlexProps","stretchHeight":true,"stretchWidth":true,},"frozen":false,"headPosition":0.0,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"name":"graphic_65618193","resourceType":"GMRSpriteGraphic","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"spriteId":{"name":"spr_bloco_pause","path":"sprites/spr_bloco_pause/spr_bloco_pause.yy",},"x":0.0,"y":0.0,},
        {"$GMRTextItem":"v3","%Name":"text_2110843D","alignment":0,"charSpacing":0.0,"colour":4283432959,"flexProperties":{"$InstanceFlexProps":"v1","anchor":1,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_titulo_creditos","path":"fonts/fnt_txt_titulo_creditos/fnt_txt_titulo_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_2110843D","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"CRÉDITOS","wrap":false,"x":-52.0,"y":32.0,},
        {"$GMRTextItem":"v3","%Name":"text_1729EE6","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_1729EE6","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"DESENVOLVEDOR","wrap":false,"x":299.25,"y":107.0,},
        {"$GMRTextItem":"v3","%Name":"text_87FC521","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_87FC521","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"QA TESTER","wrap":false,"x":322.75,"y":219.75,},
        {"$GMRTextItem":"v3","%Name":"text_77E2CBA9","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_77E2CBA9","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"ROTEIRISTA","wrap":false,"x":190.0,"y":173.5,},
        {"$GMRTextItem":"v3","%Name":"text_1042E10A","alignment":0,"charSpacing":0.0,"colour":4291582484,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_nomes_creditos","path":"fonts/fnt_txt_nomes_creditos/fnt_txt_nomes_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_1042E10A","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"GUSTAVO LIMA MENDES","wrap":false,"x":174.5,"y":192.5,},
        {"$GMRTextItem":"v3","%Name":"text_68BFC1CB","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_68BFC1CB","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"GAME DESIGNER","wrap":false,"x":31.0,"y":219.75,},
        {"$GMRTextItem":"v3","%Name":"text_14A896BB","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_14A896BB","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"SOM E EFEITOS","wrap":false,"x":176.5,"y":299.25,},
        {"$GMRTextItem":"v3","%Name":"text_19CB2B73","alignment":0,"charSpacing":0.0,"colour":4291582484,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_nomes_creditos","path":"fonts/fnt_txt_nomes_creditos/fnt_txt_nomes_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_19CB2B73","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"VICTOR BARROS BRITO","wrap":false,"x":181.0,"y":318.25,},
        {"$GMRTextItem":"v3","%Name":"text_69E18C03","alignment":0,"charSpacing":0.0,"colour":4291582484,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_nomes_creditos","path":"fonts/fnt_txt_nomes_creditos/fnt_txt_nomes_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_69E18C03","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"MARCOS ALBINO FERREIRA","wrap":false,"x":30.5,"y":235.75,},
        {"$GMRTextItem":"v3","%Name":"text_20687F32","alignment":0,"charSpacing":0.0,"colour":4294967295,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_20687F32","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"ARTISTA","wrap":false,"x":60.5,"y":107.0,},
        {"$GMRTextItem":"v3","%Name":"text_22538EB9","alignment":0,"charSpacing":0.0,"colour":4294962688,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_22538EB9","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"EQUIPE DE DESENVOLVIMENTO","wrap":false,"x":113.0,"y":70.0,},
        {"$GMRTextItem":"v3","%Name":"text_629A8FD2","alignment":0,"charSpacing":0.0,"colour":4294962688,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_creditos","path":"fonts/fnt_txt_creditos/fnt_txt_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_629A8FD2","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"ASSETS UTILIZADOS","wrap":false,"x":154.5,"y":361.0,},
        {"$GMRTextItem":"v3","%Name":"text_1773E688","alignment":257,"charSpacing":0.0,"colour":4291582484,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_nomes_creditos","path":"fonts/fnt_txt_nomes_creditos/fnt_txt_nomes_creditos.yy",},"frameH":15.0,"frameW":324.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_1773E688","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"EDINALDO DO NASCIMENTO SANTOS\r\nTEIXEIRA JÚNIOR","wrap":false,"x":272.25,"y":126.0,},
        {"$GMRTextItem":"v3","%Name":"text_7E3B8DA4","alignment":0,"charSpacing":0.0,"colour":4291582484,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_nomes_creditos","path":"fonts/fnt_txt_nomes_creditos/fnt_txt_nomes_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_7E3B8DA4","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"BRUNO DE SOUZA TEIXEIRA","wrap":false,"x":298.25,"y":235.75,},
        {"$GMRTextItem":"v3","%Name":"text_59040DE0","alignment":0,"charSpacing":0.0,"colour":4291582484,"flexProperties":{"$InstanceFlexProps":"v1","anchor":0,"resourceType":"InstanceFlexProps",},"fontId":{"name":"fnt_txt_nomes_creditos","path":"fonts/fnt_txt_nomes_creditos/fnt_txt_nomes_creditos.yy",},"frameH":0.0,"frameW":0.0,"frozen":false,"ignore":true,"inheritedItemId":null,"inheritItemSettings":false,"lineSpacing":0.0,"name":"text_59040DE0","paragraphSpacing":0.0,"resourceType":"GMRTextItem","resourceVersion":"2.0","rotation":0.0,"scaleX":1.0,"scaleY":1.0,"text":"FELIPE FERREIRA GOMES","wrap":false,"x":32.5,"y":126.0,},
      ],"flexDirection":0,"gridX":53,"gridY":8,"justifyContent":1,"name":"UILayer_menu_creditos","nodeColour":4288301298,"resourceType":"GMRUILayer","resourceVersion":"2.0","visible":false,},
  ],
  "locked":false,
  "name":"RoomUI",
  "parent":{
    "name":"Projeto Seminário",
    "path":"Projeto Seminário.yyp",
  },
  "resourceType":"GMRoomUI",
  "resourceVersion":"2.0",
  "viewspaceChildren":[],
  "visible":true,
}